function_parameter_count: 8
identifier_name:
  min_length: 2
  max_length: 50
line_length: 
  warning: 120
  ignores_comments: true
type_name:
  max_length: 50
function_parameter_count:
  warning: 9
  error: 12
large_tuple: 4

custom_rules:
  newline_after_definition_start:
    name: "There should be an empty line after defintion opening braces"
    regex: '(^[ a-zA-Z]*(?:protocol|extension|class|struct|enum) (?!(?:var|let))[ a-zA-Z:,<>\n]*\{\n *\S+)'
    severity: warning
  newline_before_definition_end:
    name: "There should be an empty line before defintion closing braces"
    regex: '^[^\n]+\n\}\n'
    severity: warning