#!/bin/sh

# Script is executed in the root folder of the project.
# If your `Pods` folder isn't in the root folder of the project,
# modify the path below so it points to where the `swiftlint` script is.

Pods/SwiftLint/swiftlint --strict
if [ "$?" = "3" ]
then
    exit -1
else
    exit 0
fi
